/* 
 * Book Service API
 *
 * This api is part of Book Service and handles all CRUD operation on book domain object
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NewBook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewBookTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewBook
        //private NewBook instance;

        public NewBookTests()
        {
            // TODO uncomment below to create an instance of NewBook
            //instance = new NewBook();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewBook
        /// </summary>
        [Fact]
        public void NewBookInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewBook
            //Assert.IsInstanceOfType<NewBook> (instance, "variable 'instance' is a NewBook");
        }


        /// <summary>
        /// Test the property 'Isbn'
        /// </summary>
        [Fact]
        public void IsbnTest()
        {
            // TODO unit test for the property 'Isbn'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Authors'
        /// </summary>
        [Fact]
        public void AuthorsTest()
        {
            // TODO unit test for the property 'Authors'
        }

    }

}
