openapi: "3.0.0"
tags:
    - name: book
      description: This will be part of book controller
    - name: author
info:
  title: Book Service API
  description: This api is part of Book Service and handles all CRUD operation on book domain object
  version: '1.0'
paths:
  /book/{id}:
    get:
      tags:
        - book
      description: Get a book by an id
      parameters:
        - name: id
          in: path
          description: ID of book to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Book'  
components:
  schemas:
    Book: 
      type: object
      required:
        - isbn
        - title
        - price
        - authors
        - id
      properties:
        isbn:
          type: number
          format: int64
          minimum: 1000
        title:
          type: string
        price:
          type: number
          format: double
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        id:
          type: integer
          format: int64
          minimum: 1
    Author:
      type: object
      required: 
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        lastName:
          type: string
        title:
          type: string

          

