openapi: "3.0.0"
tags:
    - name: book
      description: This will be part of book controller
    - name: author
info:
  title: Book Service API
  description: This api is part of Book Service and handles all CRUD operation on book domain object
  version: '1.0'
paths:
  /book:
    get:
      description: Get All Books
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      description: Saves New Book
      requestBody:
        description: user to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
      responses:
        '200':
          description: OK
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /book/{id}:
    get:
      description: Get a book by an id
      parameters:
        - name: id
          in: path
          description: ID of book to return
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Book'  
              examples:
                valid-book-1: 
                  value:
                    id: 3
                    title: "Docker for Dummies"
                    price: 15.30
                    isbn: "456789"
                    authors: 
                      - firstName: John
                        lastName: Doe
                      - firstName: Jane
                        lastName: Doe
                valid-book-2: 
                  value:
                    id: 5
                    title: "Golf for Dummies"
                    price: 7.99
                    isbn: "1234"
                    authors: 
                      - firstName: Tiger
                        lastName: Woods
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Book: 
      type: object
      required:
        - isbn
        - title
        - price
        - authors
        - id
      properties:
        isbn:
          type: string
        title:
          type: string
        price:
          type: number
          format: double
          x-faker: finance.amount
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        id:
          type: integer
          format: int64
          minimum: 1
    NewBook:
      type: object
      required:
        - isbn
        - title
        - price
        - authors
      properties:
        isbn:
          type: string
        title:
          type: string
        price:
          type: number
          format: double
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
    Author:
      type: object
      required: 
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        lastName:
          type: string
        title:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

          

